config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root -> for folder 'posts' and file 'index.html.erb'
  root 'posts#index', as: 'home'
  # get -> call url path /about for folder 'pages' and file 'about.html.erb'
  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    
    has_many :comments
    validates :title, presence:true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    # config for page 'about.html.erb'
    def about
        @title = 'About us'
        @content = 'This is about page'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    def show
        @post = Post.find(params[:id])
    end
    def new
        @post = Post.new
    end
    def create
        # render plain: params[:post].inspect

        # 'Post' represent model
        @post = Post.new(post_params)

        if(@post.save)
            redirect_to @post
        else 
            render 'new'
        end
    end
    def edit
        @post = Post.find(params[:id])
    end
    def update
        @post = Post.find(params[:id])
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to posts_path
    end
    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Blog with Ruby on Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", home_path %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          
        </ul>
        <ul class="navbar-nav navbar-right">
          <li><%= link_to "Create Post", new_post_path %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js' %>

</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger">
                <%= msg %>
            </div>
            <% end %>
                <% end %>
                    <p>
                        <%= f.label :title %>
                            <br>
                            <%= f.text_field(:title, {:class=> 'form-control'}) %>
                    </p>
                    <p>
                        <%= f.label :body %>
                            <br>
                            <%= f.text_area(:body, {:class => 'form-control'}) %>
                    </p>
                    <p>
                        <%= f.submit({:class => 'btn btn-primary'}) %>
                    </p>
    <% end %>

app/views/posts/index.html.erb
<h1>Blog Post</h1>
<% @posts.each do |post| %>
    <div class="card">
        <div class="card-header">
            <%= post.title %>
        </div>
        <div class="card-body">
            <p class="card-text"><%= post.body %></p>
            <%= link_to "Read More", post_path(post), :class=> 'btn btn-primary'%>
        </div>
    </div>
   
<% end %>

app/views/posts/new.html.erb
<h1>Add Posts</h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p> 
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class=> 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h2>
    <%= @post.title %>
</h2>
<p>
    <%= @post.body%>
</p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-light' %>
<%= link_to "Delete", post_path(@post), 
method: :delete, 
data: {confirm: 'Are you sure?'}, 
:class => 'btn btn-danger' %>

<hr>

<h1>Add Comments</h1>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :username %>
            <br>
            <%= f.text_field(:username, {:class=> 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %>
            <br>
            <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-light'}) %>
    </p>
<% end %>